
<div id="view-content">
	<p><b>Welcome</b></p>
        
      
    <div>
       
            <?php $i = 1;
            ?>
        <?php foreach($this->posts AS $row): ?>
        <?php if($i%2 == 0){
            $className = "even";
        }else{
            $className = "odd";;
        }
?>    
        <div id="<?php echo $className; ?>">
            <div><b>Title :</b> <?php echo $row->Post_Title?><span style="float:right; color: blue"></span></div>
                <b>Author :</b> <?php echo $row->Post_Author . '<br>';?>
                <b>Publish Date :</b> <?php echo $row->Post_Date . '<br>';?>
                <b>Status :</b> <?php echo $row->Post_Status ? 'published' : 'draft'; ?> <br>
                <div> <b>Content :</b><?=$row->Post_content?></div><br><br>
            </div>
        <?php $i++; ?>
        <?php endforeach; ?>
    </div>
  


    
</div>