<?php echo $this->doctype(); ?>
<html>
    <head>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <link href="/style.css" rel="stylesheet" type="text/css" />
        <title><?php echo $this->title; ?></title>
        <?php
        echo $this->dojo();
        echo $this->dojo()->addStylesheetModule('dijit.themes.tundra');
        ?>
    </head>
    <body onload="init()">

        <div id="topheader">
            <div class="logo"></div>
            <div class="menu_area">
                <?php
                $this->navigation()->menu()->setPartial(array('nav1.phtml', 'default'));
                echo $this->navigation()->menu()->render();
                ?>

            </div>
        </div>
        <div id="search_strip">
            <div class="freeregistration">
                <div class="registration"><a href="/User/register" class="free">FREE</a> Registration </div>
            </div>
            <div class="search_area">
                <div class="search_box">
                    <label>
                        <input name="textfield" type="text" class="searchtextbox" />
                    </label>
                </div>
                <div class="search_go">
                    <div align="center"><a href="#" class="go">GO</a></div>
                </div>
                <div class="search_box">&raquo; <a href="#" class="advancesearch">Advance Search</a></div>
            </div>
        </div>

        <div id="breadcrumb">You are in: 
            <?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render(); ?>
        </div>


        <div id="body_area">
            <div class="left">
                <div class="left_menutop"></div>
                <div class="left_menu_area">
                    
                    <?php
                    $rootPage = $this->navigation()->menu()->getContainer();
                    $pages = $rootPage->getPages();

                    foreach ($pages as $page) {
                        if ($page->isActive(true)) {
                            $nav2Container = $page;
                        }
                    }
                    if (isset($nav2Container)) {
                        echo $this->navigation()->menu()->renderMenu($nav2Container, array('ulClass' => 'nav2'));
                    };
                    ?>
                    <?php //echo $this->navigation()->menu();  ?>
                </div>
            </div>
            <div class="midarea">
                <div class="head"> Welcome to Zend </div>
                <div class="body_textarea">

                </div>
                <?php if (isset($this->flashMessages) && !empty($this->flashMessages)) { ?>
                    <ul id="messages">            
                        <?php foreach ($this->flashMessages as $message) { ?>
                            <li>
                                <?php echo $message; ?>
                            </li>    
                        <?php } ?>
                    </ul>
                <?php } ?>
                <div class="body_textarea">
                    <?php echo $this->layout()->content; ?>
                </div>


                <?php echo $this->homePageSpotlight; ?>
            </div>

            <div class="right">
                <div class="comments_area">
                    <div class="events_head">Events</div>
                    <div class="comments_text">
                        <div align="left">On 12th January 2008 <br />
                            <a href="#" class="comments_link">ourna tempus imperdiet llentes Pellentesque</a></div>
                    </div>
                    <div class="comments_text">
                        <div align="left">On 14th January 2008 <br />
                            <a href="#" class="comments_link">uctus pellentesque et erat nec </a></div>
                    </div>
                    <div class="comments_text">
                        <div align="left">On 16th January 2008 <br />
                            <a href="#" class="comments_link">vamus et magna et torpraesent accumsan</a></div>
                    </div>
                </div>
                <div class="login_area">
                    <div class="login_top"></div>
                    <div class="login_bodyarea">
                        <div class="right_head">
                            <div align="center">Join Us For Membership</div>
                        </div>
                        <div class="right_textbox">
                            <label>
                                <input name="textfield2" type="text" class="righttextbox" value="Name" />
                            </label>
                        </div>
                        <div class="right_textbox">
                            <label>
                                <input name="textfield22" type="password" class="righttextbox" value="Password" />
                            </label>
                        </div>
                        <div class="right_text">
                            <label>
                                <input type="checkbox" name="checkbox" value="checkbox" />
                            </label>
                            Remember Me</div>
                        <div class="right_text">
                            <div align="center"><a href="#" class="login">Login</a></div>
                        </div>
                    </div>
                    <div class="login_bottom"></div>
                </div>
                <div class="login_area">
                    <div class="login_top"></div>
                    <div class="login_bodyarea">
                        <div class="right_head">
                            <div align="center"><strong>Newsletter Signup </strong></div>
                        </div>
                        <div class="right_textbox">
                            <label>
                                <input name="textfield23" type="text" class="righttextbox" value="Email Id" />
                            </label>
                        </div>
                        <div class="right_text">
                            <div align="center"><a href="#" class="login">Signup</a></div>
                        </div>
                    </div>
                    <div class="login_bottom"></div>
                </div>
                <div class="comments_area">
                    <div class="newletter_head">Newslinks</div>
                    <div class="comments_text">
                        <div align="left"><a href="#" class="news_link">Sed massa Integer tincidunt </a></div>
                    </div>
                    <div class="comments_text">
                        <div align="left"><a href="#" class="news_link">Dapibus nunc</a></div>
                    </div>
                    <div class="comments_text">
                        <div align="left"><a href="#" class="news_link">Phasellus ac Nunc</a></div>
                    </div>
                    <div class="comments_text">
                        <div align="left"><a href="#" class="news_link">Quisque rhoncus felis in </a></div>
                    </div>
                    <div class="comments_text">
                        <div align="left"><a href="#" class="news_link">Ultricies sollicitudin diam orci </a></div>
                    </div>
                    <div class="comments_text">
                        <div align="left"><a href="#" class="news_link">Mollis risusin rhoncus velit </a></div>
                    </div>
                    <div class="comments_text">
                        <div align="left"><a href="#" class="news_link">Nulla ege</a></div>
                    </div>
                </div>
            </div>

        </div>
        <div id="fotter">
            <div class="fotter_links">
                <div align="center"><a href="#" class="fotterlink">Home</a>  |  <a href="#" class="fotterlink">About Us</a>  |  <a href="#" class="fotterlink">Companies Success</a>  |  <a href="#" class="fotterlink">Client Testimonials</a>  |  <a href="#" class="fotterlink">Methods of Development</a>  |  <a href="#" class="fotterlink">Newsletter</a>  |  <a href="#" class="fotterlink">Subscribe Info</a>  |  <a href="#" class="fotterlink">Oppotunities</a>  |  <a href="#" class="fotterlink">Current Events</a>  |  <a href="#" class="fotterlink">Contact Us</a></div>
            </div>
            <div class="fotter_copyrights">
                <div align="center">&copy; Copyright Information Goes Here. All Rights Reserved</div>
            </div>
            <div class="fotter_validation">
                <div align="center"><a href="http://validator.w3.org/check?uri=referer" target="_blank" class="xhtml">XHTML</a> <a href="http://jigsaw.w3.org/css-validator/check/referer" target="_blank" class="css">CSS</a><br />
                </div>
            </div>
            <div class="fotter_designed">
                <div align="center">Designed By : <a href="#" class="fotter_designedlink">Template World</a></div>
            </div>
        </div>


    </body>
</html>